# Generated by Django 3.2.6 on 2021-08-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210805_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='room_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
