# Generated by Django 3.2.6 on 2021-08-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_groupchat_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='room_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Group Name'),
        ),
    ]
