# Generated by Django 3.2.6 on 2021-08-05 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_alter_groupchat_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupchatmessage',
            old_name='group_name',
            new_name='room_name',
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
