# Generated by Django 3.2.6 on 2021-08-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210805_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='group_icon',
            field=models.ImageField(blank=True, default='default.png', upload_to='group_icons'),
        ),
    ]
